version: '3.8'

services:
  php-site:
    build: .
    container_name: php-site
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.support.rule=Host(`support.ptc.edu.mv`)"
      - "traefik.http.routers.support.entrypoints=websecure"
      - "traefik.http.routers.support.tls=true"
      - "traefik.http.routers.support.tls.certresolver=cloudflare"
      - "traefik.http.services.support.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
